import Head from 'next/head'
import { Children } from 'react'
import Header from './Header'

const Layout = ({ children, navigation }) => (
  <div className="bg-gray-50">
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header navigation={navigation} />
    <main className="min-h-screen px-4">{children}</main>
    <footer className="flex justify-center w-full px-2 py-6 bg-gray-200 border-t border-gray-300">
      <p>
        Labore ea irure fugiat minim ullamco commodo. @
        {new Date().getFullYear()}
      </p>
    </footer>
  </div>
)

export default Layout
